/**
 * loadData.ts — fetches solar_data.json (served from public/) and returns
 * the typed HourlyRecord array. The file is generated by the Python pipeline
 * (clean_data.py) and copied to simulator/public/ before running the dev server.
 */

import type { HourlyRecord } from './types';

export async function loadSolarData(): Promise<HourlyRecord[]> {
  const res = await fetch('/solar_data.json');
  if (!res.ok) {
    throw new Error(
      `Could not load solar_data.json (HTTP ${res.status}). ` +
      `Run the Python pipeline first: python fetch_weather.py && python clean_data.py`,
    );
  }
  const data = await res.json();
  return data as HourlyRecord[];
}
